name: Renovate Auto-merge

on:
  pull_request:
    branches: [ main, master ]

jobs:
  renovate-auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]'
    
    permissions:
      contents: write
      pull-requests: write
      checks: read

    steps:
    - name: Wait for CI
      uses: fountainhead/action-wait-for-check@v1.2.0
      id: wait-for-ci
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: test
        ref: ${{ github.event.pull_request.head.sha }}
        timeoutSeconds: 1200

    - name: Enable auto-merge for Renovate PRs
      if: steps.wait-for-ci.outputs.conclusion == 'success'
      run: |
        echo "CI passed, enabling auto-merge for renovate PR"
        gh pr merge --auto --merge "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Comment on failed CI
      if: steps.wait-for-ci.outputs.conclusion == 'failure'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🚨 **CI Failed** - Renovate PR cannot be auto-merged due to failing tests or build issues. Please review the CI logs and fix any issues.'
          })